### ISSUE TITLE
Error when entering correct Adobe ID password. 

### ISSUE THREAD

**Issue by Daniel3356** [adrienmetais/adl#12]
Hi, when I do `./adl.py login -u _______@hotmail.com` and I enter my correct password I get this :
```
Traceback (most recent call last):
  File "/Users/name/Downloads/adl/./adl.py", line 109, in <module>
    args.func(args)
  File "/Users/name/Downloads/adl/./adl.py", line 29, in adobe_login
    login.login(args.user, password)
  File "/Users/name/Downloads/adl/adl/login.py", line 31, in login
    device.activate(acc, d)
  File "/Users/name/Downloads/adl/adl/device.py", line 68, in activate
    return act.call() 
  File "/Users/name/Downloads/adl/adl/api_call.py", line 19, in call
    return self.parse(reply)
  File "/Users/name/Downloads/adl/adl/api_call.py", line 170, in parse
    self.device.device_id = tree_root.find("{http://ns.adobe.com/adept}device").text
AttributeError: 'NoneType' object has no attribute 'text'
```

and the app crush, how can I fix it?

**Comment by recolic** [comment]
same problem..

After making a debug print like this:
```
diff --git a/adl/api_call.py b/adl/api_call.py
index 1eb3c53..043ea6c 100644
--- a/adl/api_call.py
+++ b/adl/api_call.py
@@ -167,6 +167,7 @@ class Activate(APICall):
       return None
 
     tree_root = etree.fromstring(reply)
+    print("DEBUG: ",reply)
     self.device.device_id = tree_root.find("{http://ns.adobe.com/adept}device").text
     return reply  
```

It shows the error message from adobe: `<error xmlns="http://ns.adobe.com/adept" data="E_ADEPT_REQUEST_EXPIRED http://adeactivate.adobe.com/adept/Activate 2024-03-04T07:39:27+00:00%20(1709537967000)%20is%20before%202024-03-04T15:09:34+00:00%20(1709564974161)"/>`

**Comment by adrienmetais** [comment]
Thanks for the report and the debug log !
Would you mind trying branch fix_expiration_date and tell me if that fixes your issue ?
