### ISSUE TITLE
TypeError: load_der_x509_certificate() missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by samuel-gf** [adrienmetais/adl#9]
I got this issue, can you help me?

```
samuel@hp-i5:~/tmp/adl$ sudo python3 ./adl.py login -u info@my_server....blah...blah.com
Password: 
Traceback (most recent call last):
  File "./adl.py", line 109, in <module>
    args.func(args)
  File "./adl.py", line 29, in adobe_login
    login.login(args.user, password)
  File "/home/samuel/tmp/adl/adl/login.py", line 25, in login
    if not sign_in(data, acc, user, password):
  File "/home/samuel/tmp/adl/adl/login.py", line 96, in sign_in
    certificate = x509.load_der_x509_certificate(base64.b64decode(data.config.authentication_certificate))
TypeError: load_der_x509_certificate() missing 1 required positional argument: 'backend'
```

**Comment by adrienmetais** [comment]
Hello !
Can you tell me what version of the cryptography package you are using ?
You can get it with something like:
`pip show cryptography `

**Comment by samuel-gf** [comment]
I had installed version 2.8, after update with:
`pip install -U cryptography`

it worked, problem solved
